### ISSUE TITLE
Structuring of Project

### ISSUE THREAD

**Issue by nerdyninja** [stabsiesgst/material-components-web#1]
Create a structure for the repository, to make it easy to use with production or development project.
Folders to be created:
**css** - Contains Stylesheet Files - **material-components-web.css*
**js** - Contains Javascript Files - **material-components-web.js*
**demos** - with demos of each component, where each HTML file will be named on the component.
**README** - About the project

**Comment by IpshitaC** [comment]
Hi!
I'd like to be assigned to this issue.

**Comment by nerdyninja** [comment]
Hey @IpshitaC you can start working on this issue. 
also, keep checking other issues.

**Comment by pritamnegi** [comment]
I would like to work on this issue

**Comment by IpshitaC** [comment]
@nerdyninja I can't seem to be able to fork the repository. How should I start work?

**Comment by nerdyninja** [comment]
@IpshitaC you can fork now, since the repository was empty, you were not able to fork or clone.
You can go ahead now 😄

**Comment by IpshitaC** [comment]
@nerdyninja I've raised a PR for the same, please let me know if there are any more changes to be made. Thanks! :)
